name: Train
description: |
  Train a TRADE model
inputs:
  - {name: owner, description: ''}
  - {name: project, description: ''}
  - {name: experiment, description: ''}
  - {name: model, description: ''}
  - {name: pretrained_s3, description: ''}
  - {name: mode, description: ''}
  - {name: git_rev, description: ''}
  - {name: additional_args, description: ''}
outputs:
  - {name: s3_model_dir}
implementation:
  container:
    image: '932360549041.dkr.ecr.us-west-2.amazonaws.com/genie-toolkit-jupyter:epic-kitchen-train.20201209.05'
    command:
    - /bin/bash
    - -e
    - -c
    - |
      . ./lib.sh

      parse_args "$0" "owner project experiment model pretrained_s3 git_rev s3_model_dir mode" "$@"
      shift $n
      set -x

      echo "TESTING PRETRAINED MODEL"
      
      apt-get update
      apt-get install ffmpeg libsm6 libxext6  -y

      chmod +x ./download-dataset.sh
      ./download-dataset.sh

      chmod +x ./download-pretrained.sh
      ./download-pretrained.sh

      export MODEL_VERSION=${git_rev}

      chmod +x ./sync-repo.sh
      ./sync-repo.sh
      
      git clone https://github.com/facebookresearch/detectron2 /detectron2_repo
      
      pip3 install -e /detectron2_repo
      
      cd epic-kitchen-lstm
      
      # git clone https://github.com/epic-kitchens/epic-kitchens-100-annotations.git /data/epic-kitchens-100-annotations
      
      find /data/epic-kitchens-100-annotations

      if ["$mode" == "train"]; then
        if [ -n "${pretrained_s3}" ]; then
          mkdir -p output/checkpoints
          aws s3 cp --recursive "${pretrained_s3}" ./output/checkpoints/
        fi
        PYTHONPATH=./ python3 tools/run_net.py \
          --cfg configs/EPIC-KITCHENS/SLOWFAST_LSTM_8x8_R50.yaml \
          NUM_GPUS 1 \
          OUTPUT_DIR ./save \
          EPICKITCHENS.VISUAL_DATA_DIR /data/epic-kitchen-all \
          EPICKITCHENS.ANNOTATIONS_DIR /data/epic-kitchens-100-annotations \
          EPICKITCHENS.TB_DIR /shared/tensorboard/${project}/${experiment}/${owner}/${model}
      else
        if [ -n "${pretrained_s3}" ]; then
          mkdir -p test
          aws s3 cp "${pretrained_s3}/checkpoint_best.pyth" ./test/checkpoint_best.pyth
        fi
        PYTHONPATH=./ python3 tools/run_net.py \
          --cfg configs/EPIC-KITCHENS/SLOWFAST_LSTM_8x8_R50.yaml \
          NUM_GPUS 1 \
          OUTPUT_DIR ./save \
          EPICKITCHENS.VISUAL_DATA_DIR /data/epic-kitchen-all \
          EPICKITCHENS.ANNOTATIONS_DIR /data/epic-kitchens-100-annotations \
          EPICKITCHENS.TB_DIR /shared/tensorboard/${project}/${experiment}/${owner}/${model} \
          TRAIN.ENABLE False \
          TEST.ENABLE True \
          TEST.CHECKPOINT_FILE_PATH ./test/checkpoint_best.pyth
      fi


      S3_MODEL_DIR=s3://geniehai/${owner}/models/${project}/${experiment}/${model}/`date +%s`/
      aws s3 sync --no-progress save/ ${S3_MODEL_DIR}
            
      mkdir -p `dirname $s3_model_dir`
      echo ${S3_MODEL_DIR} > $s3_model_dir
    
    args: [
      'cmd',
      --owner, {inputValue: owner},
      --project, {inputValue: project},
      --experiment, {inputValue: experiment},
      --model, {inputValue: model},
      --pretrained_s3, {inputValue: pretrained_s3},
      --mode, {inputValue: mode},
      --git_rev, {inputValue: git_rev},
      --s3_model_dir, {outputPath: s3_model_dir},
      --,
      {inputValue: additional_args}, 
    ]
# --tensorboard_dir /shared/tensorboard/${project}/${experiment}/${owner}/${model}
