name: Train
description: |
  Train a TRADE model
inputs:
  - {name: owner, description: ''}
  - {name: project, description: ''}
  - {name: experiment, description: ''}
  - {name: model, description: ''}
  - {name: git_rev, description: ''}
  - {name: additional_args, description: ''}
outputs:
  - {name: s3_model_dir}
implementation:
  container:
    image: '932360549041.dkr.ecr.us-west-2.amazonaws.com/genie-toolkit-jupyter:epic-kitchen-train.20201209.05'
    command:
    - /bin/bash
    - -e
    - -c
    - |
      . ./lib.sh

      parse_args "$0" "owner project experiment model git_rev s3_model_dir" "$@"
      shift $n
      set -x
      
      apt-get update
      apt-get install ffmpeg libsm6 libxext6  -y

      chmod +x ./download-dataset.sh
      ./download-dataset.sh

      chmod +x ./download-pretrained.sh
      ./download-pretrained.sh

      export MODEL_VERSION=${git_rev}

      chmod +x ./sync-repo.sh
      ./sync-repo.sh
      
      git clone https://github.com/facebookresearch/detectron2 /detectron2_repo
      
      pip3 install -e /detectron2_repo
      
      cd epic-kitchen-lstm
      
      git clone https://github.com/epic-kitchens/epic-kitchens-100-annotations.git /data/epic-kitchens-100-annotations
      
      find /data/epic-kitchens-100-annotations

      PYTHONPATH=./ python3 tools/run_net.py \
        --cfg configs/EPIC-KITCHENS/SLOWFAST_LSTM_8x8_R50.yaml \
        NUM_GPUS 1 \
        SOLVER.BASE_LR 0.001 \
        SOLVER.MAX_EPOCH 3 \
        OUTPUT_DIR ./save \
        EPICKITCHENS.VISUAL_DATA_DIR /data/epic-kitchen-all \
        EPICKITCHENS.ANNOTATIONS_DIR /data/epic-kitchens-100-annotations \
        EPICKITCHENS.TB_DIR /shared/tensorboard/${project}/${experiment}/${owner}/${model}

      S3_MODEL_DIR=s3://geniehai/${owner}/models/${project}/${experiment}/${model}/`date +%s`/
      aws s3 sync --no-progress save/ ${S3_MODEL_DIR}
            
      mkdir -p `dirname $s3_model_dir`
      echo ${S3_MODEL_DIR} > $s3_model_dir
    
    args: [
      'cmd',
      --owner, {inputValue: owner},
      --project, {inputValue: project},
      --experiment, {inputValue: experiment},
      --model, {inputValue: model},
      --git_rev, {inputValue: git_rev},
      --s3_model_dir, {outputPath: s3_model_dir},
      --,
      {inputValue: additional_args}, 
    ]
# --tensorboard_dir /shared/tensorboard/${project}/${experiment}/${owner}/${model}
